name: 1/2 a px.
url: http://halfapx.com
encoding: utf-8
gems:
    - jekyll-autoprefixer
markdown: kramdown
kramdown:
  input: GFM
destination: jekyllbuild
keep_files: [css/main.css, js/build/main.min.js]
excerpt_separator: "<!-- more -->"
permalink: /:categories/:title/
tag_dir: /tag
img_dir: /img/posts
sass:
    style: expanded
collections:
    portfolio:
        output: true
        permalink: /portfolio/:path/
    themes:
        output: true
        permalink: /themes/:path/
    brushlettering:
        output: true
        permalink: /brushlettering/:path/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
      page-title: true
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
exclude: [js]
